services:
  ws_depthsplat:
    build:
      context: .
      dockerfile: Dockerfile
    # END docker
    volumes:
    # mount all devs for usb
      - type: bind
        source: ..
        target: /workspaces
      - type: bind
        source: /home/haubenstock/data/situationmap_data_mount
        target: /workspaces/custom
    privileged: true
    network_mode: host
    ipc: host
    pid: host
    runtime: nvidia
